# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.4.8
maven_group=drvlabs.de
archives_base_name=btscreen-fabric-26.2

# Dependencys
fabric_version=0.154.2+26.2
malilib_version=26.2-0.29.2
mod_menu_version=20.0.1
baritone_version=26.2-SNAPSHOT
nether_pathfinder_version=1.6
